// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcemhavvfcnwkdslygwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZW1oYXZ2ZmNud2tkc2x5Z3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODM4NzQsImV4cCI6MjA2MzA1OTg3NH0.eeAsQUYjndfRPeMpkGPqYe86WiTtW2w-YbmEfg3lPmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});